### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/cliente/10 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "id_cliente" : 4,
    "nome" : "Luciano",
    "cpf": "123456789-20",
    "compra_fiado": 2,
    "dia_fiado": "12/06/2023",
    "senha": "1234"
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/2 HTTP/1.1
content-type: application/json

{
    "id_cliente" : 2,
    "nome" : "Luciano",
    "cpf": "46372182139",
    "compra_fiado": 2,
    "dia_fiado": "",
    "senha": "AbcBolinhas"
}


### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/3 HTTP/1.1